#worksheet 0 - python programming and Numpy
#Name: Anu Rawal
#Student ID : 2418790

Task1 - Unit Converter Program
Step 1: Create Conversion Function


In [ ]:
def convert_units(conversion_type, value):
    """
    This function converts units of length, weight, and volume.

    Parameters:
    conversion_type (str): type of conversion
    value (float): value to convert

    Returns:
    float: converted value
    """

    if conversion_type == "m_to_ft":
        return value * 3.28084

    elif conversion_type == "ft_to_m":
        return value / 3.28084

    elif conversion_type == "kg_to_lbs":
        return value * 2.20462

    elif conversion_type == "lbs_to_kg":
        return value / 2.20462

    elif conversion_type == "l_to_gal":
        return value * 0.264172

    elif conversion_type == "gal_to_l":
        return value / 0.264172

    else:
        return "Invalid conversion type"


Step 2: Take User Input

In [ ]:
try:
    print("Choose Conversion Type")
    print("1: meters to feet")
    print("2: feet to meters")
    print("3: kg to pounds")
    print("4: pounds to kg")
    print("5: liters to gallons")
    print("6: gallons to liters")

    choice = int(input("Enter choice number: "))
    value = float(input("Enter value: "))

    if choice == 1:
        result = convert_units("m_to_ft", value)

    elif choice == 2:
        result = convert_units("ft_to_m", value)

    elif choice == 3:
        result = convert_units("kg_to_lbs", value)

    elif choice == 4:
        result = convert_units("lbs_to_kg", value)

    elif choice == 5:
        result = convert_units("l_to_gal", value)

    elif choice == 6:
        result = convert_units("gal_to_l", value)

    else:
        result = "Invalid choice"

    print("Converted value:", result)

except:
    print("Error: Please enter valid numbers")


Choose Conversion Type
1: meters to feet
2: feet to meters
3: kg to pounds
4: pounds to kg
5: liters to gallons
6: gallons to liters
Enter choice number: 1
Enter value: 50
Converted value: 164.042


TASK 2 - MAthematical Operations on List
Step 1: create functions

In [ ]:
def find_sum(numbers):
    """Returns sum of numbers"""
    return sum(numbers)

def find_average(numbers):
    """Returns average"""
    return sum(numbers) / len(numbers)

def find_max(numbers):
    """Returns maximum number"""
    return max(numbers)

def find_min(numbers):
    """Returns minimum number"""
    return min(numbers)


Step 2: User Input program

In [ ]:
try:
    nums = input("Enter numbers separated by space: ")
    numbers = list(map(float, nums.split()))

    print("Choose Operation")
    print("1 Sum")
    print("2 Average")
    print("3 Maximum")
    print("4 Minimum")

    choice = int(input("Enter choice: "))

    if choice == 1:
        print("Sum =", find_sum(numbers))

    elif choice == 2:
        print("Average =", find_average(numbers))

    elif choice == 3:
        print("Maximum =", find_max(numbers))

    elif choice == 4:
        print("Minimum =", find_min(numbers))

    else:
        print("Invalid choice")

except:
    print("Invalid input")


Enter numbers separated by space: 5
Choose Operation
1 Sum
2 Average
3 Maximum
4 Minimum
Enter choice: 2
Average = 5.0


TASK 3 - Extract every Other Element

In [ ]:
def extract_every_other(lst):
    return lst[::2]


my_list = [1,2,3,4,5,6]
result = extract_every_other(my_list)

print(result)


[1, 3, 5]


TASK 4 - Get Sublist

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]


my_list = [1,2,3,4,5,6]

print(get_sublist(my_list,2,4))


[3, 4, 5]


TASK 5 - Reverse List

In [ ]:
def reverse_list(lst):
    return lst[::-1]


my_list = [1,2,3,4,5]

print(reverse_list(my_list))


[5, 4, 3, 2, 1]


TASK 6 - Remove First and Last Element

In [ ]:
def remove_first_last(lst):
    return lst[1:-1]


my_list = [10,20,30,40,50]

print(remove_first_last(my_list))


[20, 30, 40]


7. Flatten a list of lists

In [3]:
# Function to flatten a deeply nested list
def deep_flatten(lst):

    result = []          # Final flat list
    stack = list(lst)    # Copy input into a stack

    # Process until stack is empty
    while stack:

        item = stack.pop(0)   # Take first element

        if type(item) == list:
            # If it is a list → open it and add items back to stack
            stack = item + stack
        else:
            # If it is a number → add to result
            result.append(item)

    return result


# Example input
data = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

# Call function
print(deep_flatten(data))

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested list Average

In [ ]:
# Function to find average of nested list
def average_nested(lst):

    total = 0      # to store sum of all numbers
    count = 0      # to count how many numbers

    # Go through each sublist
    for sublist in lst:

        # Go through each number inside sublist
        for num in sublist:
            total += num   # add number to total
            count += 1     # increase count

    # Calculate average
    return total / count


# Example input
data = [[1,2],[3,4],[5,6]]

# Print result
print(average_nested(data))

About a Numpy
Problem 1: Array Creation

In [5]:
# Import NumPy library
import numpy as np


# 1️⃣ Create array from a Python list
arr1 = np.array([1, 2, 3, 4, 5])
print("Array from list:", arr1)


# 2️⃣ Create array of zeros
arr2 = np.zeros(5)
print("Zeros array:", arr2)


# 3️⃣ Create array of ones
arr3 = np.ones(5)
print("Ones array:", arr3)


# 4️⃣ Create array with numbers from 0 to 9
arr4 = np.arange(10)
print("Range array:", arr4)


# 5️⃣ Create array with evenly spaced numbers
arr5 = np.linspace(0, 1, 5)
print("Linspace array:", arr5)

Array from list: [1 2 3 4 5]
Zeros array: [0. 0. 0. 0. 0.]
Ones array: [1. 1. 1. 1. 1.]
Range array: [0 1 2 3 4 5 6 7 8 9]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


Problem 2: Array Manipulation, Ranges, indexing

In [6]:
# Import NumPy
import numpy as np


# 1️⃣ Create array from 1 to 10
arr = np.arange(1, 11)
print("Original array:", arr)


# 2️⃣ Get first 5 elements
first_five = arr[:5]
print("First 5 elements:", first_five)


# 3️⃣ Get last 3 elements
last_three = arr[-3:]
print("Last 3 elements:", last_three)


# 4️⃣ Get elements from index 2 to 6
middle_part = arr[2:7]
print("Index 2 to 6:", middle_part)


# 5️⃣ Change value at index 0
arr[0] = 100
print("After changing first element:", arr)


# 6️⃣ Select every second element
every_second = arr[::2]
print("Every second element:", every_second)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
First 5 elements: [1 2 3 4 5]
Last 3 elements: [ 8  9 10]
Index 2 to 6: [3 4 5 6 7]
After changing first element: [100   2   3   4   5   6   7   8   9  10]
Every second element: [100   3   5   7   9]


Problem 3: Array operations

In [7]:
# Import NumPy
import numpy as np


# Create two arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])


# 1️⃣ Addition
add = a + b
print("Addition:", add)


# 2️⃣ Subtraction
sub = b - a
print("Subtraction:", sub)


# 3️⃣ Multiplication
mul = a * b
print("Multiplication:", mul)


# 4️⃣ Division
div = b / a
print("Division:", div)


# 5️⃣ Square of array a
square = a ** 2
print("Square of a:", square)


# 6️⃣ Sum of elements
print("Sum of a:", np.sum(a))


# 7️⃣ Maximum value
print("Max of b:", np.max(b))


# 8️⃣ Minimum value
print("Min of b:", np.min(b))

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Square of a: [ 1  4  9 16 25]
Sum of a: 15
Max of b: 50
Min of b: 10


Problem 4: matrix Operations

In [8]:
# Import NumPy
import numpy as np


# Create two matrices (2D arrays)
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])


# 1️⃣ Matrix Addition
add = A + B
print("Addition:\n", add)


# 2️⃣ Matrix Subtraction
sub = A - B
print("Subtraction:\n", sub)


# 3️⃣ Element-wise Multiplication
mul = A * B
print("Element-wise Multiplication:\n", mul)


# 4️⃣ Matrix Multiplication (Dot Product)
mat_mul = np.dot(A, B)
print("Matrix Multiplication:\n", mat_mul)


# 5️⃣ Transpose of matrix A
transpose = A.T
print("Transpose of A:\n", transpose)


# 6️⃣ Determinant of matrix A
det = np.linalg.det(A)
print("Determinant of A:", det)

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Determinant of A: -2.0000000000000004
